import argparse
import os
import random
import subprocess
import sys
from datetime import datetime
from typing import Dict, Any, Optional, Tuple

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, random_split

from data_loader import MultiModalRoboticDataset
from mamba_model import MultimodalMambaBC
from weights_registry import (
    PROJECT_ROOT,
    build_training_config,
    find_existing_weights_by_config,
    register_trained_weights,
    save_run_config,
    save_run_metrics,
)


def parse_args() -> argparse.Namespace:
    """
    Parse command-line arguments for training.

    The script supports two workflows:
    1. Run YOLO filtering first, then train on successful trajectories.
    2. Use an existing filtered CSV file, then train on successful trajectories.
    """
    parser = argparse.ArgumentParser(
        description="Train a Mamba behavioral cloning model on robotic trajectories."
    )

    # -----------------------------
    # Data and filtering arguments
    # -----------------------------
    parser.add_argument(
        "--data_dir",
        type=str,
        default=None,
        help="Root directory containing raw trajectory folders.",
    )

    parser.add_argument(
        "--filtered_csv",
        type=str,
        default=None,
        help="Path to an existing filtered CSV file produced by filter_data.py.",
    )

    parser.add_argument(
        "--run_yolo_filter",
        action="store_true",
        help="Run YOLO + gripper filtering before training.",
    )

    parser.add_argument(
        "--yolo_weights",
        type=str,
        default="src/robotics_data_prep/best.pt",
        help="Path to YOLO weights file.",
    )

    parser.add_argument(
        "--yolo_filter_threshold",
        type=float,
        default=0.0755,
        help="Stable gripper threshold used by the YOLO filtering script.",
    )

    parser.add_argument(
        "--filter_output",
        type=str,
        default="final_mamba_dataset.csv",
        help="CSV filename generated by the YOLO filtering script.",
    )

    parser.add_argument(
        "--status_filter",
        type=str,
        default="SUCCESS",
        help="Only trajectories with this Status value will be used for training.",
    )

    parser.add_argument(
        "--filter_task",
        type=str,
        default="pick_lift_success",
        help="Semantic description of the filtering task.",
    )

    # -----------------------------
    # Sequence and target arguments
    # -----------------------------
    parser.add_argument(
        "--seq_length",
        type=int,
        default=10,
        help="Temporal window length K.",
    )

    parser.add_argument(
        "--action_delay",
        type=int,
        default=0,
        help="Delay offset applied to the target action index.",
    )

    parser.add_argument(
        "--target_type",
        type=str,
        default="action_at_window_end",
        choices=["action_at_window_end", "action_next_step"],
        help="Defines which action is used as the target.",
    )

    parser.add_argument(
        "--state_source",
        type=str,
        default="state",
        choices=[
            "state",
            "qpos",
            "qpos_qvel",
            "state_qpos",
            "state_qpos_qvel",
        ],
        help="Robot-state feature source used by the dataset.",
    )

    parser.add_argument(
        "--use_robot_state",
        action="store_true",
        default=True,
        help="Use robot state features together with visual embeddings.",
    )

    # -----------------------------
    # OpenCLIP arguments
    # -----------------------------
    parser.add_argument(
        "--clip_model_name",
        type=str,
        default="ViT-B-32",
        help="OpenCLIP model architecture name.",
    )

    parser.add_argument(
        "--clip_pretrained",
        type=str,
        default="laion2b_s34b_b79k",
        help="OpenCLIP pretrained weights name.",
    )

    # -----------------------------
    # Mamba model arguments
    # -----------------------------
    parser.add_argument(
        "--d_model",
        type=int,
        default=128,
        help="Mamba hidden dimension.",
    )

    parser.add_argument(
        "--d_state",
        type=int,
        default=16,
        help="Mamba internal SSM state size.",
    )

    parser.add_argument(
        "--d_conv",
        type=int,
        default=4,
        help="Mamba local convolution width.",
    )

    parser.add_argument(
        "--expand",
        type=int,
        default=2,
        help="Mamba expansion factor.",
    )

    parser.add_argument(
        "--num_layers",
        type=int,
        default=1,
        help="Number of stacked Mamba blocks.",
    )

    parser.add_argument(
        "--dropout",
        type=float,
        default=0.0,
        help="Dropout probability.",
    )

    # -----------------------------
    # Training arguments
    # -----------------------------
    parser.add_argument(
        "--batch_size",
        type=int,
        default=16,
        help="Training batch size.",
    )

    parser.add_argument(
        "--learning_rate",
        type=float,
        default=0.001,
        help="Optimizer learning rate.",
    )

    parser.add_argument(
        "--max_epochs",
        type=int,
        default=100,
        help="Maximum number of epochs.",
    )

    parser.add_argument(
        "--patience",
        type=int,
        default=5,
        help="Early stopping patience.",
    )

    parser.add_argument(
        "--weight_decay",
        type=float,
        default=0.0,
        help="Weight decay regularization value.",
    )

    parser.add_argument(
        "--gradient_clip",
        type=float,
        default=None,
        help="Optional gradient clipping value.",
    )

    parser.add_argument(
        "--mixed_precision",
        type=str,
        default="none",
        choices=["none", "fp16", "bf16"],
        help="Mixed precision mode.",
    )

    parser.add_argument(
        "--train_split",
        type=float,
        default=0.8,
        help="Train split ratio.",
    )

    parser.add_argument(
        "--split_strategy",
        type=str,
        default="random_window_split",
        help="Dataset split strategy description.",
    )

    parser.add_argument(
        "--random_seed",
        type=int,
        default=42,
        help="Random seed for reproducibility.",
    )

    parser.add_argument(
        "--num_workers",
        type=int,
        default=0,
        help="Number of DataLoader workers. Keep 0 when OpenCLIP runs inside Dataset.",
    )

    # -----------------------------
    # Checkpoint arguments
    # -----------------------------
    parser.add_argument(
        "--run_name",
        type=str,
        default=None,
        help="Optional run name. If omitted, a timestamp-based name is generated.",
    )

    parser.add_argument(
        "--force_train",
        action="store_true",
        help="Train even if a checkpoint with the same config already exists.",
    )

    parser.add_argument(
        "--resume_checkpoint",
        type=str,
        default=None,
        help="Path to last_checkpoint.pth for resuming training from the last completed epoch.",
    )

    return parser.parse_args()


def set_random_seed(seed: int) -> None:
    """
    Set random seeds for reproducible experiments.
    """
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def project_path(path_value: str) -> str:
    """
    Convert a relative project path to an absolute path.
    """
    if os.path.isabs(path_value):
        return path_value

    return os.path.join(PROJECT_ROOT, path_value)


def run_yolo_filter_if_needed(args: argparse.Namespace) -> Optional[str]:
    """
    Run the YOLO filtering script if requested.

    Returns:
        Path to the filtered CSV file if available.
        Otherwise, None.
    """
    if not args.run_yolo_filter:
        return args.filtered_csv

    if not args.data_dir:
        raise ValueError("--data_dir is required when --run_yolo_filter is used.")

    filter_script_path = os.path.join(
        PROJECT_ROOT,
        "src",
        "robotics_data_prep",
        "filter_data.py",
    )

    if not os.path.exists(filter_script_path):
        raise FileNotFoundError(
            f"Could not find filtering script: {filter_script_path}"
        )

    yolo_weights_path = project_path(args.yolo_weights)

    if not os.path.exists(yolo_weights_path):
        raise FileNotFoundError(
            f"Could not find YOLO weights file: {yolo_weights_path}"
        )

    output_filename = os.path.basename(args.filter_output)

    command = [
        sys.executable,
        filter_script_path,
        "--data_dir",
        args.data_dir,
        "--weights",
        yolo_weights_path,
        "--threshold",
        str(args.yolo_filter_threshold),
        "--output",
        output_filename,
    ]

    print("\nRunning YOLO-based trajectory filtering...")
    print("Command:")
    print(" ".join(command))

    subprocess.run(command, check=True)

    generated_csv_path = os.path.join(args.data_dir, output_filename)

    if not os.path.exists(generated_csv_path):
        raise FileNotFoundError(
            f"YOLO filter completed, but CSV was not found: {generated_csv_path}"
        )

    print(f"Filtered CSV created at: {generated_csv_path}")

    return generated_csv_path


def create_run_paths(run_name: str) -> Dict[str, str]:
    """
    Create paths for one training run.

    Returns:
        Dictionary with run_dir, model_path, config_path, metrics_path, and log_path.
    """
    run_dir = os.path.join(PROJECT_ROOT, "checkpoints", run_name)
    logs_dir = os.path.join(PROJECT_ROOT, "outputs", "logs")

    os.makedirs(run_dir, exist_ok=True)
    os.makedirs(logs_dir, exist_ok=True)

    return {
        "run_dir": run_dir,
        "model_path": os.path.join(run_dir, "model.pth"),
        "config_path": os.path.join(run_dir, "config.json"),
        "metrics_path": os.path.join(run_dir, "metrics.json"),
        "log_path": os.path.join(logs_dir, f"{run_name}.txt"),
    }


def get_amp_dtype(mixed_precision: str):
    """
    Return the torch dtype used for automatic mixed precision.
    """
    if mixed_precision == "fp16":
        return torch.float16

    if mixed_precision == "bf16":
        return torch.bfloat16

    return None


def build_dataset(args: argparse.Namespace, filtered_csv_path: Optional[str]) -> MultiModalRoboticDataset:
    """
    Build the dataset used for training.

    If a filtered CSV is provided, only rows matching status_filter are used.
    Otherwise, raw trajectories are scanned from data_dir.
    """
    if filtered_csv_path:
        print(f"\nLoading dataset from filtered CSV: {filtered_csv_path}")
        return MultiModalRoboticDataset(
            csv_path=filtered_csv_path,
            status_filter=args.status_filter,
            seq_length=args.seq_length,
            action_delay=args.action_delay,
            target_type=args.target_type,
            state_source=args.state_source,
            clip_model_name=args.clip_model_name,
            clip_pretrained=args.clip_pretrained,
            use_robot_state=args.use_robot_state,
        )

    if not args.data_dir:
        raise ValueError("Either --filtered_csv or --data_dir must be provided.")

    print(f"\nLoading dataset from raw data directory: {args.data_dir}")
    return MultiModalRoboticDataset(
        data_root=args.data_dir,
        seq_length=args.seq_length,
        action_delay=args.action_delay,
        target_type=args.target_type,
        state_source=args.state_source,
        clip_model_name=args.clip_model_name,
        clip_pretrained=args.clip_pretrained,
        use_robot_state=args.use_robot_state,
    )


def train_one_run(args: argparse.Namespace) -> None:
    """
    Train one Mamba behavioral cloning model.
    """
    set_random_seed(args.random_seed)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\nUsing device: {device}")

    if device.type == "cpu":
        print("Warning: Training Mamba on CPU may be very slow or unsupported.")

    filtered_csv_path = run_yolo_filter_if_needed(args)

    dataset = build_dataset(args, filtered_csv_path)
    dataset_stats = dataset.get_stats()

    if len(dataset) == 0:
        raise ValueError("Dataset contains zero training windows.")

    train_size = int(args.train_split * len(dataset))
    val_size = len(dataset) - train_size

    if train_size <= 0 or val_size <= 0:
        raise ValueError(
            "Invalid train/validation split. "
            "Both train and validation must contain at least one sample."
        )

    split_generator = torch.Generator().manual_seed(args.random_seed)

    train_dataset, val_dataset = random_split(
        dataset,
        [train_size, val_size],
        generator=split_generator,
    )

    train_loader = DataLoader(
        train_dataset,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
    )

    dataset_name = (
        os.path.basename(filtered_csv_path)
        if filtered_csv_path
        else os.path.basename(os.path.abspath(args.data_dir))
    )

    config = build_training_config(
        dataset_name=dataset_name,
        seq_length=args.seq_length,
        action_delay=args.action_delay,
        target_type=args.target_type,

        input_dim=dataset_stats["input_dim"],
        visual_embedding_dim=dataset_stats["visual_embedding_dim"],
        robot_state_dim=dataset_stats["robot_state_dim"],
        feature_fusion="openclip_plus_state_concat",
        state_source=args.state_source,
        use_robot_state=args.use_robot_state,

        clip_model_name=args.clip_model_name,
        clip_pretrained=args.clip_pretrained,
        freeze_clip=True,

        d_model=args.d_model,
        d_state=args.d_state,
        d_conv=args.d_conv,
        expand=args.expand,
        num_layers=args.num_layers,
        dropout=args.dropout,
        action_dim=dataset_stats["action_dim"],

        batch_size=args.batch_size,
        learning_rate=args.learning_rate,
        max_epochs=args.max_epochs,
        patience=args.patience,
        optimizer="Adam",
        loss_function="MSELoss",
        weight_decay=args.weight_decay,
        gradient_clip=args.gradient_clip,
        mixed_precision=args.mixed_precision,

        train_split=args.train_split,
        split_strategy=args.split_strategy,
        random_seed=args.random_seed,

        extra_config={
            "use_yolo_filter": bool(args.run_yolo_filter or filtered_csv_path is not None),
            "status_filter": args.status_filter if filtered_csv_path else None,
            "filter_task": args.filter_task if filtered_csv_path else None,
            "yolo_filter_threshold": args.yolo_filter_threshold if filtered_csv_path else None,
        },
    )

    existing_item = find_existing_weights_by_config(config)

    # When resuming, we intentionally continue the same run even if a matching
    # best model already exists in the registry.
    if existing_item is not None and not args.force_train and not args.resume_checkpoint:
        print("\nA checkpoint with the same configuration already exists.")
        print(f"Run name: {existing_item.get('run_name')}")
        print(f"Weights: {existing_item.get('weights_path')}")
        print("Use --force_train if you want to train again anyway.")
        return

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    if args.resume_checkpoint and not args.run_name:
        resume_path_for_name = project_path(args.resume_checkpoint)
        run_name = os.path.basename(os.path.dirname(resume_path_for_name))
    else:
        run_name = args.run_name or (
            f"run_{timestamp}_k{args.seq_length}_d{args.d_model}_lr{args.learning_rate}"
        )

    paths = create_run_paths(run_name)

    relative_model_path = os.path.relpath(paths["model_path"], PROJECT_ROOT)
    relative_config_path = os.path.relpath(paths["config_path"], PROJECT_ROOT)
    relative_metrics_path = os.path.relpath(paths["metrics_path"], PROJECT_ROOT)

    save_run_config(relative_config_path, config)

    model = MultimodalMambaBC(
        input_dim=config["input_dim"],
        d_model=config["d_model"],
        action_dim=config["action_dim"],
        d_state=config["d_state"],
        d_conv=config["d_conv"],
        expand=config["expand"],
        num_layers=config["num_layers"],
        dropout=config["dropout"],
    ).to(device)

    criterion = nn.MSELoss()
    optimizer = optim.Adam(
        model.parameters(),
        lr=args.learning_rate,
        weight_decay=args.weight_decay,
    )

    amp_dtype = get_amp_dtype(args.mixed_precision)
    use_amp = device.type == "cuda" and amp_dtype is not None

    scaler = torch.cuda.amp.GradScaler(
        enabled=(use_amp and args.mixed_precision == "fp16")
    )

    best_val_loss = float("inf")
    best_epoch = 0
    patience_counter = 0
    history = []
    start_epoch = 1

    if args.resume_checkpoint:
        resume_path = project_path(args.resume_checkpoint)
        if not os.path.exists(resume_path):
            raise FileNotFoundError(f"Resume checkpoint was not found: {resume_path}")

        print(f"\nResuming training from: {resume_path}")
        resume_state = torch.load(resume_path, map_location=device, weights_only=False)
        model.load_state_dict(resume_state["model_state_dict"])
        optimizer.load_state_dict(resume_state["optimizer_state_dict"])

        if "scaler_state_dict" in resume_state and resume_state["scaler_state_dict"] is not None:
            try:
                scaler.load_state_dict(resume_state["scaler_state_dict"])
            except Exception as exc:
                print(f"Warning: could not restore AMP scaler state: {exc}")

        best_val_loss = float(resume_state.get("best_val_loss", best_val_loss))
        best_epoch = int(resume_state.get("best_epoch", best_epoch))
        patience_counter = int(resume_state.get("patience_counter", patience_counter))
        history = list(resume_state.get("history", history))
        start_epoch = int(resume_state.get("epoch", 0)) + 1
        print(f"Continuing from epoch {start_epoch}/{args.max_epochs}")

    print("\nStarting training...")
    print(f"Train windows: {train_size}")
    print(f"Validation windows: {val_size}")
    print(f"Run directory: {paths['run_dir']}")

    with open(paths["log_path"], "w", encoding="utf-8") as log_file:
        log_file.write(f"Run name: {run_name}\n")
        log_file.write(f"Device: {device}\n")
        log_file.write(f"Config: {config}\n\n")
        log_file.write("epoch,train_loss,val_loss,status\n")

        for epoch in range(start_epoch, args.max_epochs + 1):
            model.train()
            total_train_loss = 0.0

            for inputs, targets in train_loader:
                inputs = inputs.to(device)
                targets = targets.to(device)

                optimizer.zero_grad()

                if use_amp:
                    with torch.autocast(
                        device_type="cuda",
                        dtype=amp_dtype,
                        enabled=True,
                    ):
                        outputs = model(inputs)
                        loss = criterion(outputs, targets)

                    scaler.scale(loss).backward()

                    if args.gradient_clip is not None:
                        scaler.unscale_(optimizer)
                        torch.nn.utils.clip_grad_norm_(
                            model.parameters(),
                            args.gradient_clip,
                        )

                    scaler.step(optimizer)
                    scaler.update()

                else:
                    outputs = model(inputs)
                    loss = criterion(outputs, targets)
                    loss.backward()

                    if args.gradient_clip is not None:
                        torch.nn.utils.clip_grad_norm_(
                            model.parameters(),
                            args.gradient_clip,
                        )

                    optimizer.step()

                total_train_loss += loss.item()

            avg_train_loss = total_train_loss / len(train_loader)

            model.eval()
            total_val_loss = 0.0

            with torch.no_grad():
                for inputs, targets in val_loader:
                    inputs = inputs.to(device)
                    targets = targets.to(device)

                    if use_amp:
                        with torch.autocast(
                            device_type="cuda",
                            dtype=amp_dtype,
                            enabled=True,
                        ):
                            outputs = model(inputs)
                            loss = criterion(outputs, targets)
                    else:
                        outputs = model(inputs)
                        loss = criterion(outputs, targets)

                    total_val_loss += loss.item()

            avg_val_loss = total_val_loss / len(val_loader)

            status = "no_improvement"

            if avg_val_loss < best_val_loss:
                best_val_loss = avg_val_loss
                best_epoch = epoch
                patience_counter = 0
                status = "new_best"

                torch.save(
                    {
                        "model_state_dict": model.state_dict(),
                        "config": config,
                        "best_val_loss": best_val_loss,
                        "best_epoch": best_epoch,
                    },
                    paths["model_path"],
                )

            else:
                patience_counter += 1

            history.append(
                {
                    "epoch": epoch,
                    "train_loss": float(avg_train_loss),
                    "val_loss": float(avg_val_loss),
                    "status": status,
                }
            )

            # Save a resume checkpoint after every completed epoch.
            # This is different from model.pth, which stores the best model only.
            torch.save(
                {
                    "epoch": epoch,
                    "model_state_dict": model.state_dict(),
                    "optimizer_state_dict": optimizer.state_dict(),
                    "scaler_state_dict": scaler.state_dict() if scaler is not None else None,
                    "best_val_loss": best_val_loss,
                    "best_epoch": best_epoch,
                    "patience_counter": patience_counter,
                    "history": history,
                    "config": config,
                    "run_name": run_name,
                },
                os.path.join(paths["run_dir"], "last_checkpoint.pth"),
            )

            print(
                f"Epoch {epoch}/{args.max_epochs} | "
                f"Train Loss: {avg_train_loss:.6f} | "
                f"Val Loss: {avg_val_loss:.6f} | "
                f"{status}"
            )
            print(
                f"[TRAIN_PROGRESS] Epoch {epoch}/{args.max_epochs} | "
                f"Patience: {patience_counter}/{args.patience} | "
                f"Best epoch: {best_epoch} | Best val loss: {best_val_loss:.6f}",
                flush=True,
            )

            log_file.write(
                f"{epoch},{avg_train_loss:.6f},{avg_val_loss:.6f},{status}\n"
            )
            log_file.flush()

            if patience_counter >= args.patience:
                print(f"Early stopping triggered at epoch {epoch}.")
                break

    metrics = {
        "run_name": run_name,
        "best_val_loss": float(best_val_loss),
        "best_epoch": int(best_epoch),
        "epochs_ran": len(history),
        "num_trajectories": dataset_stats["num_trajectories"],
        "num_windows": dataset_stats["num_windows"],
        "num_train_windows": train_size,
        "num_val_windows": val_size,
        "dataset_stats": dataset_stats,
        "history": history,
    }

    save_run_metrics(relative_metrics_path, metrics)

    register_trained_weights(
        run_name=run_name,
        weights_path=relative_model_path,
        config=config,
        best_loss=float(best_val_loss),
        config_path=relative_config_path,
        metrics_path=relative_metrics_path,
        status="available",
        overwrite_existing=False,
    )

    print("\nTraining complete.")
    print(f"Best validation loss: {best_val_loss:.6f}")
    print(f"Best epoch: {best_epoch}")
    print(f"Model saved to: {paths['model_path']}")
    print(f"Config saved to: {paths['config_path']}")
    print(f"Metrics saved to: {paths['metrics_path']}")
    print(f"Log saved to: {paths['log_path']}")


def main() -> None:
    """
    Entry point for training.
    """
    args = parse_args()
    train_one_run(args)


if __name__ == "__main__":
    main()